### ISSUE TITLE
【专项漏洞检测】没有按照设置的扫描目标地址请求，目标地址有子路径，实际扫描请求仍然只到根目录

### ISSUE THREAD

**Issue by xjh1994** [yaklang/yakit#1901]
扫描目标地址是https+域名+/api/test，但是实际漏扫的时候，请求仍然是到域名根目录的，没有请求到子路径。
请问是设计如此吗？在“额外参数”中设置了请求路径，也不行

扫描目标
![image](https://github.com/user-attachments/assets/bb3a02ea-e33d-4237-8860-01b3ead46737)

额外参数
![image](https://github.com/user-attachments/assets/1101cf30-8670-4379-8bf9-797eeb065d19)

扫描结果
![image](https://github.com/user-attachments/assets/8016393f-2df7-452a-93a4-45e6f0056109)

**Comment by xjh1994** [comment]
Nuclei Yaml插件：

```yaml
http:
- raw:
  - |+
    @timeout: 30s
    GET /xxx/xxx HTTP/1.1
    Content-Type: application/json
```
